spring:
    profiles:
        active: dev
    application:
        name: yunlian-truck-websocket
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        locale: zh
        default-property-inclusion: non_null

    http:
      multipart:
        max-file-size: 20MB
        max-request-size: 20MB
        enabled: true

    datasource:
        name: dev
        url: jdbc:mysql://localhost:3306/qihuanlian?useUnicode=true&characterEncoding=UTF8
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

    jpa:
        hibernate:
          ddl-auto: update
          dialect: org.hibernate.dialect.MySQL5Dialect
        show-sql : true

server:
    port: 8877

eureka:
    instance:
        statusPageUrlPath: /info
        healthCheckUrlPath: /health
        preferIpAddress: true
#        lease-expiration-duration-in-seconds: 10
#        lease-renewal-interval-in-seconds: 5
        # docker 部署开启
#        prefer-ip-address: true
#        ip-address: 127.0.0.1
    client:
        registerWithEureka: true
        fetchRegistry: true
#        initial-instance-info-replication-interval-seconds: 5
#        eureka-service-url-poll-interval-seconds: 5
#        registry-fetch-interval-seconds: 5
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
                    # docker 部署开启
#            defaultZone: http://center:8761/eureka/

feign:
  hystrix:
    enabled: false


hystrix:
  command:
    default:
      execution:
        isolation:
#          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 50000




